## closure : 중단하다, 폐쇄하다

scope를 생각해봅시다.

내부 함수에서는 외부 함수의 변수를 사용할 수 있습니다.

쉽게 생각해 전역변수는 어디서나 사용할 수 있죠.

```tsx
let outer = function() {
  let a = 1;

  let inner = function() {
    let b = 5;
    let c = 6;

    a = a + b + c;
    console.log(a);
  }

  inner();
}

outer(); // 12
```

예시 코드를 보면 outer 안에 inner가 있기에 inner에서 변수 a를 자유롭게 사용이 가능합니다.

> 그런데, 만약 내부 함수가 외부 함수보다 오래 살아 있는경우,
외부함수에 있던 변수들은 어떻게 될까요?
> 

그게 어떤 상황일까요? 바로 이런 상황이죠

```tsx
let outer = function() {
  let a = 1;

  let inner = function() {
    let b = 5;
    let c = 6;

    a = a + b + c;
    console.log(a);
  }

  return inner;
}

let newInner = outer();

newInner(); // 12
1. nowInner는 outer의 실행결과. 즉 inner 
2. 이는 inner가 실행 된다는 의미에요.
3. 그런데 return으로 inner를 실행했기에 outer는 파괴가 되요.
4. 즉, inner는 살아있지만 outer는 파괴된 상황이에요. (특히 변수 a!!)
```

# 🤔

외부 함수(`outer`)의 변수들은 더 이상 사용이 안되는 걸까?

가비지 컬렉터가 정리해 버린걸까요?

# 🤭

내부함수 `Inner` 는 외부함수 `outer`가 이미 반환된 후에도

`outer`의 `a`에 대한 접근 권한을 가집니다!

<aside>
🔥 바로 함수는 자신을 포함하는 함수의 스코프에 접근할 수 있기 때문입니다!!

</aside>

`return`으로 인해 `outer`의 함수가 메모리에서 해지되었지만

`inner`함수는 여전히 `outer` 함수에 `a`라는 변수의 접근권한을 갖고 있다.

### 클로저를 한마디로 표현한다면?

> 폐쇄된 공간에 대한 접근 권한을 가진 함수를 말합니다!
> 

> 이러한 특징을 이용한다면 비공개 데이터를 가진 객체를 만들어 볼 수 있습니다.
> 

```tsx
let person = (function(){
  let age = 15;

  return {
    name: "luffy",

    getAge: function(){
      console.log(age);
      return age;
    },

    setAge: function(val){
      age = val;
      console.log(age);
    }
  }
})();

pserson.getAge(); // 15
pserson.setAge(20); // 20

person.age = 30;
// 외부 함수 안에 있는 변수값을 직접 설정을 했는데도 결과는 15가 나옵니다.
// 왜냐하면 외부 함수는 이미 파괴되었기 때문입니다.
// 따라서 외부 함수의 내부 함수에서만이 접근 권한을 갖게 됩니다. 

pserson.getAge(); // 15
```

### 정리해 봅시다.

- JS는 내부 함수에서 자신을 포함하는 외부 함수의 스코프에 접근 할 수 있습니다.
- 내부 함수가 살아있는 상태에서 외부 함수가 파괴되면 외부 함수의 변수들에 대한 접근 권한은 내부 함수만 가지게 됩니다.
- 이렇게 폐쇄된 공간에 대한 접근 권한을 가진 함수가 클로저입니다.